### PR TITLE
Solves issue #144

### LINKED ISSUE #144: Links should be built with Tools function for HTTP protocol
## Expected behaviour
Links should be built with Tools function for HTTP protocol

## Actual behaviour
There are stille some "http://" hardcoded

## Steps to reproduce the behaviour
Search code source for "http://"

### PR DESCRIPTION
**Pull request by Vincent-Profileo**
# Fixes #144

## Changes made
Used Tools::getCurrentUrlProtocolPrefix() for HTTP or HTTPs

### CODE REVIEW

File: shoppingfluxexport.php [hunk 1]
```diff
@@ -213,7 +213,7 @@ public function getContent()
         $status = is_object($status_xml) ? $status_xml->Response->Status : '';
         $price = is_object($status_xml) ? (float)$status_xml->Response->Price : 0;
 
-        switch ($status) {
+        /*switch ($status) {
```
Comment (clement-hollander) [inline shoppingfluxexport.php]: @Vincent-Coll il faut supprimer le code si en commentaire, merci

**Review by clement-hollander — CHANGES_REQUESTED** [review]
